spring:
  data:
    cassandra:
  cassandra:
    keyspace-name: main
    #clientId
    username: FvsCdXBLoPokDFcdwlmHGOCU
    #clinet secret
    password: UIJXMJW+LLJWEXuA.G_f1EBZ7nJOdmPQrTsvCTDs24rFeb7+s+0.KfshDnNkIoEJ9z,2EwjoTPFmlbK1G4J4v2Hc2f.vHfwXEOgMQ5NMG5F127pkxJYd.ZicoTsnrGqa
    schema-action: create_if_not_exists
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 6e0e8773924fb82a814d
            client-secret: ae68f815ae55d7714301d47b93df45b3d19f0e3b
#    request:
#      timeout: 10s
#    connection:
#      connect-timeout: 10s
#      init-query-timeout: 10s




datadump:
  location:
    author: C:\Users\radoj\IdeaProjects\BookTracker\src\main\resources\test-authors.txt
    works: C:\Users\radoj\IdeaProjects\BookTracker\src\main\resources\test-works.txt

datastax:
  astra:
    secure-connect-bundle: secure-connect.zip

astra:
  db:
    id: AstraCS:FvsCdXBLoPokDFcdwlmHGOCU:56fc52ed3de83fb81f31892a4761c69c0c886e67eea147b05b2dd6083910653f
    region: europe-west1
    keyspace: main
    application:
      token: AstraCS:FvsCdXBLoPokDFcdwlmHGOCU:56fc52ed3de83fb81f31892a4761c69c0c886e67eea147b05b2dd6083910653f

